import Head from 'next/head'
import Intro from '../Components/Intro'
import Main from '../Components/Main'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="w-screen">
    <div className={styles.container}>
      <Head>
        <title>Home | Kamal Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="main
    h-screen flex flex-col justify-center items-center"
      >
        <Main />
      </div>
      <div id="AboutMe" className="bg-white py-10">
        <Intro />
      </div>
    </div>
    </div>
  );
}
